#!/bin/bash

echo "=================================="
echo "Instrucciones para crear Pool Uniswap v4"
echo "=================================="
echo ""
echo "Este script te guiará por los pasos necesarios para crear un pool"
echo "de Uniswap v4 con el par VCOP/USDC en Base Sepolia."
echo ""
echo "Sigue estos pasos en orden:"
echo ""
echo "1. Instalar dependencias de Uniswap v4:"
echo "   ./install-uniswap-deps.sh"
echo ""
echo "2. Instalar dependencia para consultar direcciones:"
echo "   npm install axios"
echo ""
echo "3. Consultar direcciones actuales de Uniswap v4:"
echo "   node get-uniswap-addresses.js"
echo ""
echo "4. Actualizar las direcciones en script/CreateUniswapV4Pool.s.sol"
echo "   con las obtenidas en el paso anterior."
echo ""
echo "5. Ejecutar el script de creación del pool:"
echo "   forge script script/CreateUniswapV4Pool.s.sol --rpc-url \$BASE_SEPOLIA_RPC_URL --broadcast --verify"
echo ""
echo "6. Verificar la creación del pool en el explorador de bloques."
echo ""
echo "-----------------------------------"
echo "Para más detalles, consulta el archivo UNISWAP_POOL.md"
echo "-----------------------------------" 